name = "GriddingMachine"
uuid = "f20cf718-bf4d-4727-bc8f-485b1f283ac6"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
NetCDF = "0.10"
julia = "1.3"
