name = "GriddingMachine"
uuid = "f20cf718-bf4d-4727-bc8f-485b1f283ac6"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArchGDAL = "0.5"
BenchmarkTools = "0.5"
DocStringExtensions = "0.8"
HTTP = "0.8"
NetCDF = "0.10"
Parameters = "0.12"
ProgressMeter = "1.3"
julia = "1.3"
